import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ColorProvider } from "./context/ColorContext";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <ColorProvider>
                    <header className="w-full h-16 bg-white text-gray-900 border-b-1 border-gray-200 dark:bg-gray-900 dark:text-gray-100 dark:border-gray-700">
                        <div className="mx-auto px-4 flex items-center justify-center h-full">
                            <h1 className="text-xl font-semibold">Shade Generator</h1>
                        </div>
                    </header>
                    <div className="flex justify-center min-h-screen bg-gray-100 dark:bg-gray-900">
                        {children}
                    </div>
                </ColorProvider>
            </body>
            <script src="https://accounts.google.com/gsi/client" async></script>
        </html>
    );
}
