import type { Metadata } from "next";
//import { Geist, Geist_Mono } from "next/font/google";
import { Work_Sans } from "next/font/google";
import "./globals.css";
import { Providers } from "./context/Providers";

const workSans = Work_Sans({
    variable: "--font-work-sans",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${workSans.variable} ${workSans.variable} antialiased`}>
                <Providers>
                    <div className="flex justify-center min-h-screen bg-background">
                        {children}
                    </div>
                </Providers>
            </body>
            <script src="https://accounts.google.com/gsi/client" async></script>
        </html>
    );
}
